language: ruby
rvm:
  - 2.0
#   - 2.1.5
script: "rake spec"
branches:
  only:
    - master
env:
  - PUPPET_VERSION=2.7.17
  - PUPPET_VERSION=2.7.13
  - PUPPET_VERSION=2.7.9
  - PUPPET_VERSION=2.6.9
notifications:
  email: false
gemfile: Gemfile
